// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuef9xokq6FDBSwVNkCs2WDN786w76w2Q',
    appId: '1:927581488486:web:c00833b9089c8bd50634a7',
    messagingSenderId: '927581488486',
    projectId: 'scimathinx',
    authDomain: 'scimathinx.firebaseapp.com',
    storageBucket: 'scimathinx.firebasestorage.app',
    measurementId: 'G-MEPLKSLLTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwdlP-qlpZt2-WwWa3zzdNObozYVKsmE',
    appId: '1:927581488486:android:0fe4d4d3c2c56ac00634a7',
    messagingSenderId: '927581488486',
    projectId: 'scimathinx',
    storageBucket: 'scimathinx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1t-IibKY1tOPKFwpPQAdti4XX5TKw0co',
    appId: '1:927581488486:ios:cf84de1ee60920a30634a7',
    messagingSenderId: '927581488486',
    projectId: 'scimathinx',
    storageBucket: 'scimathinx.firebasestorage.app',
    iosBundleId: 'com.scimathix.scimathix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1t-IibKY1tOPKFwpPQAdti4XX5TKw0co',
    appId: '1:927581488486:ios:cf84de1ee60920a30634a7',
    messagingSenderId: '927581488486',
    projectId: 'scimathinx',
    storageBucket: 'scimathinx.firebasestorage.app',
    iosBundleId: 'com.scimathix.scimathix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuef9xokq6FDBSwVNkCs2WDN786w76w2Q',
    appId: '1:927581488486:web:e68c2135ff5b35520634a7',
    messagingSenderId: '927581488486',
    projectId: 'scimathinx',
    authDomain: 'scimathinx.firebaseapp.com',
    storageBucket: 'scimathinx.firebasestorage.app',
    measurementId: 'G-ETP5FG7Y6R',
  );
}
